currency:
  name:
    singular: Emerald
    plural: Emeralds
  digits: 2
  denominations:
    388: 1
    133: 9
transactiontax:
  flat: 0.0
  rate: 0.0
startingbalance:
  player: 0
  faction: 0
  town: 0
  nation: 0
usevault:
  container: true
  enderchest: true
