name: Gringotts
author: jastice, squidicuz, eXeC64
version: 0.1
depend: []
main: net.mcw.gringotts.Gringotts

commands:
  balance:
    description: Shows your vault balance
    usage: /balance
  money:
    aliases: [money]
    description: Money actions
    usage: /money [add|remove]
    
permissions:
    gringotts.admin: false