name: Gringotts
authors: [jasticE, squidicuz, eXeC64]
website: https://github.com/MinecraftWars/Gringotts

version: 1.2.1-SNAPSHOT
main: org.gestern.gringotts.Gringotts

depend: []
softdepend: [Factions]

commands:
  balance:
    description: Shows your vault balance
    usage: /balance
    aliases: money
  money:
    aliases: [money]
    description: Money actions
    usage: |
      /money
      /money pay <amount> <player>
  moneyadmin:
    aliases: [moneyadm]
    description: Gringotts admin actions
    usage: |
      /moneyadm add <amount> <player>
      /moneyadm rm <amount> <player>
      /moneyadm b <player>
    permission: gringotts.admin
  gringotts:
    aliases: [grin]
    usage: |
      /grin reload
    permission: gringotts.admin

permissions:
  gringotts.createvault:
    description: Create vaults
    default: true
    children:
      gringotts.createvault.player: true
      gringotts.createvault.faction: true
  gringotts.createvault.player:
    description: Create player vaults
    default: true
  gringotts.createvault.faction:
    description: Create faction vaults
    default: true
  gringotts.usevault:
    description: Use any type of vault
    default: true
    children:
      gringotts.usevault.container: true
      gringotts.usevault.inventory: true
      gringotts.usevault.enderchest: true
  gringotts.usevault.inventory:
    description: Use player's inventory as 'vault'
    default: true
  gringotts.usevault.enderchest:
    description: Use player's enderchest inventory as vault
    default: true
  gringotts.transfer:
    description: Allow money transfer commands
    default: true
  gringotts.admin:
    description: Use all /moneyadmin commands
    default: op
